{
 "title": "Self-Hosted GitHub Runners",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "Disk Space Usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "container_fs_usage_bytes{name=~\"cadvisor-poc.+\"}",
     "legendFormat": "{{ name }}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "container_memory_usage_bytes{name=~\"cadvisor-poc.+\"}",
     "legendFormat": "{{ name }}"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(container_cpu_user_seconds_total{name=~\"cadvisor-poc.+\"}[1m])",
     "legendFormat": "{{ name }}"
    }
   ]
  },
  {
   "title": "IN Bytes Per Minute",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(container_network_receive_bytes_total{name=~\"cadvisor-poc.+\"}[1m]) != 0",
     "legendFormat": "{{ name }}"
    }
   ]
  },
  {
   "title": "OUT Bytes Per Minute",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(container_network_transmit_bytes_total{name=~\"cadvisor-poc.+\"}[1m]) != 0",
     "legendFormat": "{{ name }}"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "table",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 9 },
   "targets": [
    {
     "expr": "time() - container_start_time_seconds{name=~\"cadvisor-poc.+\"}",
     "legendFormat": "{{ name }}"
    }
   ]
  }
 ]
}